import type { MenuItem, Seat } from "./types";

const extraShot = { id: "mod_shot", label: "Extra shot", price: 3 };
const double = { id: "mod_double", label: "Double", price: 4 };
const rocks = { id: "mod_rocks", label: "Rocks", price: 0 };
const neat = { id: "mod_neat", label: "Neat", price: 0 };
const topShelf = { id: "mod_top", label: "Top shelf", price: 4 };
const saltRim = { id: "mod_salt", label: "Salt rim", price: 0 };
const spicy = { id: "mod_spicy", label: "Spicy", price: 1 };
const noIce = { id: "mod_noice", label: "No ice", price: 0 };

export const SEATS: Seat[] = [
  { id: "walkup", label: "Walk-up", kind: "walkup", capacity: 1 },
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `bar-${i + 1}`,
    label: `Bar ${i + 1}`,
    kind: "bar" as const,
    capacity: 1,
  })),
  ...Array.from({ length: 6 }, (_, i) => ({
    id: `booth-${i + 1}`,
    label: `Booth ${i + 1}`,
    kind: "booth" as const,
    capacity: i < 2 ? 6 : 4,
  })),
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `t-${i + 1}`,
    label: `T${i + 1}`,
    kind: "table" as const,
    capacity: 4,
  })),
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `patio-${i + 1}`,
    label: `Patio ${i + 1}`,
    kind: "patio" as const,
    capacity: 4,
  })),
];

export const SERVERS = ["Alex", "Jordan", "Sam", "Riley", "Casey", "Morgan"];

export const LOCAL_CATALOG: MenuItem[] = [
  {
    id: "draft_pils",
    sku: "DFT-PILS",
    name: "House Pilsner",
    category: "draft",
    price: 7,
    happyHourPrice: 5,
    description: "Crisp 16oz pour",
    popular: true,
    source: "local",
  },
  {
    id: "draft_ipa",
    sku: "DFT-IPA",
    name: "West Coast IPA",
    category: "draft",
    price: 8,
    happyHourPrice: 6,
    description: "Pine + citrus",
    popular: true,
    source: "local",
  },
  {
    id: "draft_stout",
    sku: "DFT-STT",
    name: "Nitro Stout",
    category: "draft",
    price: 8,
    happyHourPrice: 6,
    source: "local",
  },
  {
    id: "draft_lager",
    sku: "DFT-LGR",
    name: "Mexican Lager",
    category: "draft",
    price: 7,
    happyHourPrice: 5,
    modifiers: [saltRim],
    source: "local",
  },
  {
    id: "draft_sour",
    sku: "DFT-SOR",
    name: "Raspberry Sour",
    category: "draft",
    price: 9,
    happyHourPrice: 7,
    source: "local",
  },
  {
    id: "bot_heineken",
    sku: "BTL-HNK",
    name: "Heineken",
    category: "bottles",
    price: 7,
    source: "local",
  },
  {
    id: "bot_corona",
    sku: "BTL-COR",
    name: "Corona",
    category: "bottles",
    price: 7,
    source: "local",
  },
  {
    id: "bot_highlife",
    sku: "BTL-HL",
    name: "Miller High Life",
    category: "bottles",
    price: 5,
    happyHourPrice: 4,
    popular: true,
    source: "local",
  },
  {
    id: "bot_cid",
    sku: "BTL-CID",
    name: "Angry Orchard",
    category: "bottles",
    price: 7,
    source: "local",
  },
  {
    id: "wine_house_w",
    sku: "WIN-HW",
    name: "House White",
    category: "wine",
    price: 9,
    happyHourPrice: 7,
    source: "local",
  },
  {
    id: "wine_house_r",
    sku: "WIN-HR",
    name: "House Red",
    category: "wine",
    price: 9,
    happyHourPrice: 7,
    source: "local",
  },
  {
    id: "wine_bubbles",
    sku: "WIN-BUB",
    name: "Prosecco",
    category: "wine",
    price: 11,
    source: "local",
  },
  {
    id: "wine_pinot",
    sku: "WIN-PNT",
    name: "Pinot Noir",
    category: "wine",
    price: 13,
    source: "local",
  },
  {
    id: "cktl_oldfash",
    sku: "CTL-OF",
    name: "Old Fashioned",
    category: "cocktails",
    price: 14,
    popular: true,
    modifiers: [extraShot, topShelf],
    source: "local",
  },
  {
    id: "cktl_marg",
    sku: "CTL-MRG",
    name: "House Margarita",
    category: "cocktails",
    price: 13,
    happyHourPrice: 10,
    popular: true,
    modifiers: [extraShot, saltRim, spicy, noIce],
    source: "local",
  },
  {
    id: "cktl_espresso",
    sku: "CTL-ESP",
    name: "Espresso Martini",
    category: "cocktails",
    price: 15,
    modifiers: [extraShot],
    source: "local",
  },
  {
    id: "cktl_negroni",
    sku: "CTL-NEG",
    name: "Negroni",
    category: "cocktails",
    price: 14,
    source: "local",
  },
  {
    id: "cktl_whiskey_s",
    sku: "CTL-WS",
    name: "Whiskey Sour",
    category: "cocktails",
    price: 13,
    modifiers: [extraShot],
    source: "local",
  },
  {
    id: "cktl_gin",
    sku: "CTL-GT",
    name: "Gin & Tonic",
    category: "cocktails",
    price: 12,
    happyHourPrice: 9,
    modifiers: [extraShot],
    source: "local",
  },
  {
    id: "cktl_spritz",
    sku: "CTL-SPZ",
    name: "Aperol Spritz",
    category: "cocktails",
    price: 13,
    source: "local",
  },
  {
    id: "cktl_paloma",
    sku: "CTL-PAL",
    name: "Paloma",
    category: "cocktails",
    price: 13,
    modifiers: [spicy, saltRim],
    source: "local",
  },
  {
    id: "spi_jameson",
    sku: "SPI-JAM",
    name: "Jameson",
    category: "spirits",
    price: 10,
    modifiers: [rocks, neat, double],
    source: "local",
  },
  {
    id: "spi_makers",
    sku: "SPI-MAK",
    name: "Maker's Mark",
    category: "spirits",
    price: 12,
    modifiers: [rocks, neat, double],
    source: "local",
  },
  {
    id: "spi_tito",
    sku: "SPI-TIT",
    name: "Tito's",
    category: "spirits",
    price: 10,
    modifiers: [rocks, double],
    source: "local",
  },
  {
    id: "spi_casamigos",
    sku: "SPI-CAS",
    name: "Casamigos Blanco",
    category: "spirits",
    price: 14,
    modifiers: [rocks, neat, double],
    source: "local",
  },
  {
    id: "spi_henny",
    sku: "SPI-HEN",
    name: "Hennessy VS",
    category: "spirits",
    price: 14,
    modifiers: [rocks, neat, double],
    source: "local",
  },
  {
    id: "shot_well",
    sku: "SHT-WEL",
    name: "Well Shot",
    category: "shots",
    price: 6,
    happyHourPrice: 5,
    popular: true,
    source: "local",
  },
  {
    id: "shot_tequila",
    sku: "SHT-TEQ",
    name: "Tequila Shot",
    category: "shots",
    price: 8,
    source: "local",
  },
  {
    id: "shot_fireball",
    sku: "SHT-FIR",
    name: "Fireball",
    category: "shots",
    price: 7,
    source: "local",
  },
  {
    id: "shot_pickle",
    sku: "SHT-PKL",
    name: "Pickleback",
    category: "shots",
    price: 8,
    source: "local",
  },
  {
    id: "na_soda",
    sku: "NA-SOD",
    name: "Fountain Soda",
    category: "na",
    price: 3,
    source: "local",
  },
  {
    id: "na_water",
    sku: "NA-H2O",
    name: "Sparkling Water",
    category: "na",
    price: 4,
    source: "local",
  },
  {
    id: "na_na_beer",
    sku: "NA-BER",
    name: "Athletic NA IPA",
    category: "na",
    price: 7,
    source: "local",
  },
  {
    id: "food_fries",
    sku: "FOD-FRY",
    name: "Fries",
    category: "food",
    price: 8,
    popular: true,
    source: "local",
  },
  {
    id: "food_wings",
    sku: "FOD-WNG",
    name: "Wings (8)",
    category: "food",
    price: 14,
    modifiers: [spicy],
    source: "local",
  },
  {
    id: "food_pretzel",
    sku: "FOD-PRZ",
    name: "Soft Pretzel",
    category: "food",
    price: 9,
    source: "local",
  },
  {
    id: "food_burger",
    sku: "FOD-BRG",
    name: "Bar Burger",
    category: "food",
    price: 16,
    source: "local",
  },
];

export const EXISTING_POS_EXTRAS: MenuItem[] = [
  {
    id: "draft_hazy",
    sku: "DFT-HZY",
    name: "Hazy IPA",
    category: "draft",
    price: 9,
    happyHourPrice: 7,
    description: "From existing POS",
    source: "existing-pos",
  },
  {
    id: "cktl_paper",
    sku: "CTL-PPL",
    name: "Paper Plane",
    category: "cocktails",
    price: 14,
    description: "From existing POS",
    source: "existing-pos",
  },
  {
    id: "food_nachos",
    sku: "FOD-NCH",
    name: "Loaded Nachos",
    category: "food",
    price: 15,
    description: "From existing POS",
    source: "existing-pos",
  },
];

export const CATEGORY_META: Record<
  MenuItem["category"],
  { label: string; accent: string }
> = {
  draft: { label: "Draft", accent: "bg-amber-500/20 text-amber-200" },
  bottles: { label: "Bottles", accent: "bg-yellow-500/15 text-yellow-100" },
  wine: { label: "Wine", accent: "bg-rose-500/20 text-rose-200" },
  cocktails: { label: "Cocktails", accent: "bg-fuchsia-500/15 text-fuchsia-200" },
  spirits: { label: "Spirits", accent: "bg-sky-500/15 text-sky-200" },
  shots: { label: "Shots", accent: "bg-orange-500/20 text-orange-200" },
  na: { label: "N/A", accent: "bg-emerald-500/15 text-emerald-200" },
  food: { label: "Food", accent: "bg-lime-500/15 text-lime-200" },
};
