export const venue = {
  name: "199X Coffee+Bar",
  city: "Davao City",
  area: "Downtown Davao",
  phone: "+63 82 123 199X",
  email: "hello@199x.bar",
  address: "199X Coffee+Bar, Downtown Davao City",
  hours: [
    { days: "Mon – Thu", time: "10:00 AM – 12:00 MN" },
    { days: "Fri – Sat", time: "10:00 AM – 2:00 AM" },
    { days: "Sunday", time: "10:00 AM – 10:00 PM" },
  ],
  happyHour: "5:00 – 7:00 PM daily",
};

export const services = [
  {
    id: "coffee",
    color: "text-kada-green",
    title: "Specialty coffee",
    body: "Single-origin pour-overs, espresso, and cold brew from Mindanao farms. Morning service that still looks like 199X after dark.",
    items: ["Espresso & milk drinks", "Pour-over flights", "Cold brew & tonic", "Pastries until 6 PM"],
  },
  {
    id: "bar",
    color: "text-kada-red",
    title: "Cocktails & beer",
    body: "A full bar after sunset. House signatures, whiskey, wine, and ice-cold San Miguel with happy-hour prices from 5 to 7.",
    items: ["Signature cocktails", "Whiskey & wine", "Local & import beer", "Happy hour 5–7 PM"],
  },
  {
    id: "kitchen",
    color: "text-kada-orange",
    title: "All-day kitchen",
    body: "Share plates that work for a laptop afternoon or a late set. Fries, wings, and bar food built to travel across the floor.",
    items: ["Bar snacks", "Wings & fries", "Late-night plates", "Vegetarian options"],
  },
  {
    id: "private",
    color: "text-kada-yellow",
    title: "Private events",
    body: "Birthdays, brand nights, and closed-door dinners. The VIP room or a full buyout, with a dedicated server and tab.",
    items: ["VIP room", "Full venue buyout", "Custom cocktail menu", "Dedicated staff"],
  },
  {
    id: "corporate",
    color: "text-kada-blue",
    title: "Corporate & groups",
    body: "Day sessions that turn into drinks. Projector, reserved tables, and a single bill when the meeting is over.",
    items: ["Reserved tables", "Group tabs", "Day-to-night packages", "Invoice on request"],
  },
  {
    id: "nights",
    color: "text-kada-green",
    title: "Live nights",
    body: "DJs, vinyl, and guest bartenders. Regular Friday gold hour and Saturday live sets through the festival season.",
    items: ["Weekly residencies", "Guest DJs", "Vinyl sessions", "Festival takeovers"],
  },
];

export const menu = [
  {
    id: "coffee",
    name: "Coffee",
    color: "text-kada-green",
    items: [
      { name: "Espresso", price: 90, note: "Double shot" },
      { name: "Americano", price: 110 },
      { name: "Latte", price: 140 },
      { name: "Cappuccino", price: 140 },
      { name: "Cold brew", price: 150 },
      { name: "Mindanao pour-over", price: 180, note: "Single origin" },
    ],
  },
  {
    id: "cocktails",
    name: "Cocktails",
    color: "text-kada-red",
    items: [
      { name: "Mojito", price: 250, note: "Happy hour ₱200" },
      { name: "Margarita", price: 280, note: "Happy hour ₱220" },
      { name: "Long Island", price: 320 },
      { name: "Martini", price: 260 },
      { name: "Espresso martini", price: 280 },
    ],
  },
  {
    id: "beer",
    name: "Beer",
    color: "text-kada-blue",
    items: [
      { name: "San Miguel Pale Pilsen", price: 120, note: "Happy hour ₱90" },
      { name: "San Miguel Light", price: 120, note: "Happy hour ₱90" },
      { name: "Red Horse", price: 100, note: "Happy hour ₱80" },
      { name: "Corona", price: 140 },
    ],
  },
  {
    id: "spirits",
    name: "Whiskey & wine",
    color: "text-kada-yellow",
    items: [
      { name: "Jack Daniel's", price: 300 },
      { name: "Johnnie Walker Black", price: 350 },
      { name: "Jameson", price: 280 },
      { name: "House white", price: 220 },
      { name: "House red", price: 220 },
    ],
  },
  {
    id: "food",
    name: "Kitchen",
    color: "text-kada-orange",
    items: [
      { name: "Fries", price: 150 },
      { name: "Wings", price: 280 },
      { name: "Club burger", price: 320 },
    ],
  },
];

export const events = [
  {
    id: "gold-hour",
    date: "Every Friday",
    time: "5:00 PM – 9:00 PM",
    title: "Gold Hour",
    tag: "Weekly",
    color: "border-kada-yellow",
    body: "House pours, gold light, and the 199X playlist. First round happy-hour priced until 7.",
  },
  {
    id: "live-saturday",
    date: "Every Saturday",
    time: "9:00 PM – 2:00 AM",
    title: "Live Saturday",
    tag: "Weekly",
    color: "border-kada-red",
    body: "Guest DJs and a packed floor. Reserve a table or take a standing tab at the bar.",
  },
  {
    id: "coffee-flight",
    date: "Every Sunday",
    time: "10:00 AM – 1:00 PM",
    title: "Sunday Coffee Flight",
    tag: "Weekly",
    color: "border-kada-green",
    body: "Three Mindanao origins, pour-over, and a quiet room before the week starts.",
  },
  {
    id: "kadayawan-after-dark",
    date: "15 August 2026",
    time: "8:00 PM – 2:00 AM",
    title: "Kadayawan After Dark",
    tag: "Festival",
    color: "border-kada-blue",
    body: "The festival night at 199X. Special menu, guest bartenders, and a late close.",
  },
  {
    id: "vinyl-espresso",
    date: "22 August 2026",
    time: "3:00 PM – 7:00 PM",
    title: "Vinyl & Espresso",
    tag: "Special",
    color: "border-kada-orange",
    body: "Afternoon records, espresso martinis, and a short tasting flight from the bar.",
  },
  {
    id: "private-buyout",
    date: "On request",
    time: "Your schedule",
    title: "Private Buyout",
    tag: "Private",
    color: "border-kada-yellow",
    body: "Close the room for a brand night, birthday, or dinner. We set the menu and the tab.",
  },
];
