import type { ClubState } from "./types";

export function seedState(): ClubState {
  return {
    venue: {
      name: "199X Kadayawan",
      city: "Davao City",
      taxRate: 0.12,
      serviceRate: 0.1,
    },
    staff: [
      { id: "u_owner", name: "Aria Cruz", role: "owner", pin: "0000", active: true },
      { id: "u_mgr", name: "Marco Reyes", role: "manager", pin: "1111", active: true },
      { id: "u_cash", name: "John Santos", role: "cashier", pin: "2222", active: true },
      { id: "u_bar", name: "Lina Gomez", role: "bartender", pin: "3333", active: true },
      { id: "u_srv", name: "Paolo Tan", role: "server", pin: "4444", active: true },
    ],
    categories: [
      { id: "beer", name: "Beer", emoji: "🍺" },
      { id: "cocktails", name: "Cocktails", emoji: "🍹" },
      { id: "whiskey", name: "Whiskey", emoji: "🥃" },
      { id: "wine", name: "Wine", emoji: "🍷" },
      { id: "food", name: "Food", emoji: "🍔" },
    ],
    products: [
      { id: "p_smp", sku: "BER-SMP", name: "San Miguel Pale Pilsen", categoryId: "beer", price: 120, happyHourPrice: 90, cost: 45, unit: "bottle", inventory: 320, minimumStock: 40, active: true },
      { id: "p_sml", sku: "BER-SML", name: "San Miguel Light", categoryId: "beer", price: 120, happyHourPrice: 90, cost: 46, unit: "bottle", inventory: 210, minimumStock: 30, active: true },
      { id: "p_rh", sku: "BER-RH", name: "Red Horse", categoryId: "beer", price: 100, happyHourPrice: 80, cost: 40, unit: "bottle", inventory: 160, minimumStock: 30, active: true },
      { id: "p_cor", sku: "BER-COR", name: "Corona", categoryId: "beer", price: 140, cost: 70, unit: "bottle", inventory: 80, minimumStock: 16, active: true },
      { id: "p_moj", sku: "CTL-MOJ", name: "Mojito", categoryId: "cocktails", price: 250, happyHourPrice: 200, cost: 85, unit: "glass", inventory: 0, minimumStock: 0, active: true, recipeId: "r_moj" },
      { id: "p_mar", sku: "CTL-MAR", name: "Margarita", categoryId: "cocktails", price: 280, happyHourPrice: 220, cost: 90, unit: "glass", inventory: 0, minimumStock: 0, active: true, recipeId: "r_mar" },
      { id: "p_li", sku: "CTL-LI", name: "Long Island", categoryId: "cocktails", price: 320, cost: 110, unit: "glass", inventory: 0, minimumStock: 0, active: true, recipeId: "r_li" },
      { id: "p_mtn", sku: "CTL-MTN", name: "Martini", categoryId: "cocktails", price: 260, cost: 95, unit: "glass", inventory: 0, minimumStock: 0, active: true },
      { id: "p_jd", sku: "WHS-JD", name: "Jack Daniel's", categoryId: "whiskey", price: 300, cost: 140, unit: "shot", inventory: 48, minimumStock: 8, active: true },
      { id: "p_jwb", sku: "WHS-JWB", name: "Johnnie Walker Black", categoryId: "whiskey", price: 350, cost: 170, unit: "shot", inventory: 36, minimumStock: 6, active: true },
      { id: "p_jam", sku: "WHS-JAM", name: "Jameson", categoryId: "whiskey", price: 280, cost: 130, unit: "shot", inventory: 40, minimumStock: 8, active: true },
      { id: "p_hw", sku: "WIN-HW", name: "House White", categoryId: "wine", price: 220, cost: 80, unit: "glass", inventory: 28, minimumStock: 6, active: true },
      { id: "p_hr", sku: "WIN-HR", name: "House Red", categoryId: "wine", price: 220, cost: 80, unit: "glass", inventory: 24, minimumStock: 6, active: true },
      { id: "p_fry", sku: "FOD-FRY", name: "Fries", categoryId: "food", price: 150, cost: 40, unit: "plate", inventory: 60, minimumStock: 10, active: true },
      { id: "p_wng", sku: "FOD-WNG", name: "Wings", categoryId: "food", price: 280, cost: 95, unit: "plate", inventory: 40, minimumStock: 8, active: true },
      { id: "p_brg", sku: "FOD-BRG", name: "Club Burger", categoryId: "food", price: 320, cost: 110, unit: "plate", inventory: 35, minimumStock: 8, active: true },
    ],
    ingredients: [
      { id: "i_rum", name: "White Rum", unit: "ml", stock: 7500, minimumStock: 1500, cost: 1.2 },
      { id: "i_teq", name: "Tequila", unit: "ml", stock: 1500, minimumStock: 750, cost: 1.6 },
      { id: "i_vod", name: "Vodka", unit: "ml", stock: 4000, minimumStock: 750, cost: 1.1 },
      { id: "i_gin", name: "Gin", unit: "ml", stock: 3000, minimumStock: 750, cost: 1.3 },
      { id: "i_lime", name: "Lime Juice", unit: "ml", stock: 1800, minimumStock: 500, cost: 0.15 },
      { id: "i_syr", name: "Sugar Syrup", unit: "ml", stock: 2000, minimumStock: 400, cost: 0.08 },
      { id: "i_mint", name: "Mint", unit: "g", stock: 500, minimumStock: 80, cost: 0.2 },
      { id: "i_soda", name: "Soda", unit: "ml", stock: 12000, minimumStock: 2000, cost: 0.02 },
      { id: "i_trip", name: "Triple Sec", unit: "ml", stock: 1200, minimumStock: 300, cost: 0.9 },
    ],
    recipes: [
      {
        id: "r_moj",
        productId: "p_moj",
        items: [
          { ingredientId: "i_rum", qty: 50 },
          { ingredientId: "i_lime", qty: 25 },
          { ingredientId: "i_syr", qty: 15 },
          { ingredientId: "i_mint", qty: 5 },
          { ingredientId: "i_soda", qty: 100 },
        ],
      },
      {
        id: "r_mar",
        productId: "p_mar",
        items: [
          { ingredientId: "i_teq", qty: 45 },
          { ingredientId: "i_trip", qty: 20 },
          { ingredientId: "i_lime", qty: 25 },
        ],
      },
      {
        id: "r_li",
        productId: "p_li",
        items: [
          { ingredientId: "i_vod", qty: 20 },
          { ingredientId: "i_gin", qty: 20 },
          { ingredientId: "i_rum", qty: 20 },
          { ingredientId: "i_teq", qty: 20 },
          { ingredientId: "i_trip", qty: 15 },
          { ingredientId: "i_lime", qty: 20 },
        ],
      },
    ],
    tables: [
      { id: "t01", label: "T01", section: "floor", seats: 4, status: "available" },
      { id: "t02", label: "T02", section: "floor", seats: 4, status: "available" },
      { id: "t03", label: "T03", section: "floor", seats: 4, status: "available" },
      { id: "t04", label: "T04", section: "floor", seats: 4, status: "available" },
      { id: "t05", label: "T05", section: "floor", seats: 6, status: "available" },
      { id: "t06", label: "T06", section: "floor", seats: 6, status: "available" },
      { id: "vip1", label: "VIP 1", section: "vip", seats: 8, status: "available" },
      { id: "vip2", label: "VIP 2", section: "vip", seats: 8, status: "reserved" },
      { id: "bar", label: "BAR", section: "bar", seats: 12, status: "available" },
    ],
    orders: [],
    txns: [],
    nextOrder: 1245,
    nextTab: 125,
  };
}
